### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by BenoitMC** [agilidee/dorsale-seed#7]
Faire un fichier de seed avec des données de démo.

Faire un reset de la base à intervalle régulier. Toutes les heures ? Toutes les nuits ?

**Comment by BenoitMC** [comment]
J'ai commencé le script de seed, il faut encore rajouter des choses dedans.
Je suis pas certain qu'il se lance toutes les nuits sur Heroku, on verra demain.

**Comment by bgantaume** [comment]
En effet ce n'est pas le cas.
Bonne idée de mettre des données au départ. Sinon c'est pauvre.
#++

2015-04-29 19:23 GMT+02:00 Benoit MARTIN-CHAVE <notifications@github.com>:

> J'ai commencé le script de seed, il faut encore rajouter des choses dedans.
> Je suis pas certain qu'il se lance toutes les nuits sur Heroku, on verra
> demain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agilidee/dorsale-seed/issues/7#issuecomment-97511044>.
>



-- 
Benoit @gantaume <http://twitter.com/gantaume>
Catalyseur d'agilité
+33.6.76.31.22.91
http://www.agilidee.com

**Comment by BenoitMC** [comment]
C'est gratuit mais ils veulent une carte.

```
Item could not be created:
Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify
```

@bgantaume J'ai demandé le transfert pour que tu sois proprio.

**Comment by BenoitMC** [comment]
Ca seed ! :)
